source:
  type: mysql
  hostname: 172.16.1.67
  port: 3306
  username: root
  password: dsap2018
  tables: mostest_gsms.*
  server-id: 6400-6404
  server-time-zone: UTC
  scan.startup.mode: specific-offset
  scan.startup.specific-offset.file: mysql-bin.005273
  scan.startup.specific-offset.pos: 0

sink:
  type: kafka
  name: Kafka
  properties.bootstrap.servers: 172.16.1.118:9092
  properties.compression.type: lz4
  topic: kafka-default-press

pipeline:
  name: sync mysql cdc to kafka
  parallelism: 2