source:
  type: mysql
  hostname: localhost
  port: 3306
  username: flink-cdc
  password: flink-cdc@120
  tables: flink_cdc.*
  server-id: 5400-5404
  server-time-zone: UTC
  scan.startup.mode: specific-offset
  scan.startup.specific-offset.file: binlog.000165
  scan.startup.specific-offset.pos: 0

sink:
  type: kafka
  name: Kafka
  properties.bootstrap.servers: 172.16.1.118:9092
  properties.compression.type: lz4
  topic: kafka-default-press

pipeline:
  name: sync mysql cdc to kafka
  parallelism: 2