source:
  type: console
  name: console
sink:
  type: kafka
  name: Kafka-sink
  properties.bootstrap.servers: 172.16.1.135:9092,172.16.1.118:9092,172.16.1.149:9092
  properties.compression.type: lz4
  properties.max.request.size: 41943040
  properties.max.message.bytes: 41943040
  topic: kafka-press
pipeline:
  name: sync mos 67 mostest to kafka
  parallelism: 2
  channel.capacity: 10
